// <auto-generated />
using System;
using Bartender.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bartender.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220901025408_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Bartender.Models.BarMenueModel", b =>
                {
                    b.Property<int>("CocktailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CocktailDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CocktailName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CocktailPrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CocktailID");

                    b.ToTable("BarMenue");
                });

            modelBuilder.Entity("Bartender.Models.BarQueueModel", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CocktailDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("CocktailID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CocktailName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderID");

                    b.ToTable("BarQueue");
                });

            modelBuilder.Entity("Bartender.Models.BarStaff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StaffPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StaffID");

                    b.ToTable("BarStaff");
                });
#pragma warning restore 612, 618
        }
    }
}
